image: ghcr.io/kubesphere/ks-jenkins-gitpod:sha-ee0a2d3

tasks:
  - init: |
      git config --global user.name $GIT_AUTHOR_NAME
      git config --global user.email $GIT_COMMITTER_EMAIL
      gh repo fork --remote
      jcli cwp --install-artifacts --config-path formula.yaml || true

vscode:
  extensions:
    - eamodio.gitlens
